Config.RoleArmories = {
    enabled = true,
    command = 'rolearmory',
    roles = {
        civ = {
            label = 'Ammu-Nation',
            items = {
                { name = 'radio' },
                { name = 'ammo-9' },
                { name = 'ammo-38' },
                { name = 'ammo-44' },
                { name = 'ammo-45' },
                { name = 'ammo-shotgun' },
                { name = 'WEAPON_KNIFE' },
                { name = 'WEAPON_BAT' },
                { name = 'WEAPON_CROWBAR' },
                { name = 'WEAPON_GOLFCLUB' },
                { name = 'WEAPON_MACHETE' },
                { name = 'WEAPON_SWITCHBLADE' },
                { name = 'WEAPON_PISTOL', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
                { name = 'WEAPON_SNSPISTOL', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
                { name = 'WEAPON_VINTAGEPISTOL', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
                { name = 'WEAPON_DOUBLEACTION', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
                { name = 'WEAPON_REVOLVER', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
                { name = 'WEAPON_PUMPSHOTGUN', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
                { name = 'WEAPON_MUSKET', metadata = { registered = true, roleArmory = 'Ammu-Nation' } },
            },
        },
        pd = {
            label = 'Police Armory',
            groups = { police = 0 },
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
                { name = 'handcuffs' },
                { name = 'handcuff_key' },
                { name = 'cable_ties' },
                { name = 'ammo-9' },
                { name = 'ammo-rifle' },
                { name = 'ammo-shotgun' },
                { name = 'ammo-grenade' },
                { name = 'WEAPON_FLASHLIGHT' },
                { name = 'WEAPON_NIGHTSTICK' },
                { name = 'WEAPON_TASER7', metadata = armoryWeaponMetadata('Police Armory', taserGreen) },
                { name = 'WEAPON_COMBATPISTOL', metadata = armoryWeaponMetadata('Police Armory', pistolLight) },
                { name = 'WEAPON_CARBINERIFLE', metadata = armoryWeaponMetadata('Police Armory', riflePatrol) },
                { name = 'WEAPON_LSPD40MM' },
                { name = 'WEAPON_LSSD40MM' },
                { name = 'WEAPON_GRENADELAUNCHER_SMOKE' },
                { name = 'WEAPON_LESSLAUNCHER' },
                { name = 'WEAPON_LSPDBB' },
                { name = 'WEAPON_LSSDBB' },
                { name = 'WEAPON_FLASHBANG_MYRES' },
            },
        },
        so = {
            label = 'Sheriff Armory',
            groups = { police = 0 },
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
                { name = 'handcuffs' },
                { name = 'handcuff_key' },
                { name = 'cable_ties' },
                { name = 'ammo-9' },
                { name = 'ammo-rifle' },
                { name = 'ammo-shotgun' },
                { name = 'ammo-grenade' },
                { name = 'WEAPON_FLASHLIGHT' },
                { name = 'WEAPON_NIGHTSTICK' },
                { name = 'WEAPON_STUNGUN', metadata = armoryWeaponMetadata('Sheriff Armory', taserGold) },
                { name = 'WEAPON_TASER7', metadata = armoryWeaponMetadata('Sheriff Armory', taserGold) },
                { name = 'WEAPON_M18_BCSO', metadata = armoryWeaponMetadata('Sheriff Armory', pistolLight) },
                { name = 'WEAPON_AR15_BCSO', metadata = armoryWeaponMetadata('Sheriff Armory', riflePatrol) },
                { name = 'WEAPON_BCSO40MM' },
                { name = 'WEAPON_GRENADELAUNCHER_SMOKE' },
                { name = 'WEAPON_LESSLAUNCHER' },
                { name = 'WEAPON_BEANBAG' },
                { name = 'WEAPON_FLASHBANG_MYRES' },
            },
        },
        hp = {
            label = 'Highway Patrol Armory',
            groups = { sheriff = 0 },
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
                { name = 'handcuffs' },
                { name = 'handcuff_key' },
                { name = 'cable_ties' },
                { name = 'ammo-9' },
                { name = 'ammo-rifle' },
                { name = 'ammo-shotgun' },
                { name = 'ammo-grenade' },
                { name = 'WEAPON_FLASHLIGHT' },
                { name = 'WEAPON_NIGHTSTICK' },
                { name = 'WEAPON_TASER7', metadata = armoryWeaponMetadata('Highway Patrol Armory', taserGold) },
                { name = 'WEAPON_COMBATPISTOL', metadata = armoryWeaponMetadata('Highway Patrol Armory', pistolLight) },
                { name = 'WEAPON_CARBINERIFLE', metadata = armoryWeaponMetadata('Highway Patrol Armory', riflePatrol) },
                { name = 'WEAPON_TACTICALRIFLE', metadata = armoryWeaponMetadata('Highway Patrol Armory', riflePatrol) },
                { name = 'WEAPON_SAHPBB' },
                { name = 'WEAPON_PROLASER4' },
            },
        },
        fib = {
            label = 'FIB Armory',
            groups = { police = 0 },
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
                { name = 'handcuffs' },
                { name = 'handcuff_key' },
                { name = 'cable_ties' },
                { name = 'WEAPON_PROLASER4' },
                { name = 'ammo-9' },
                { name = 'ammo-rifle' },
                { name = 'WEAPON_FLASHLIGHT' },
                { name = 'WEAPON_STUNGUN' },
                { name = 'WEAPON_COMBATPISTOL' },
                { name = 'WEAPON_CARBINERIFLE' },
                { name = 'WEAPON_TACTICALRIFLE' },
                { name = 'WEAPON_MP9' },
                { name = 'WEAPON_FLASHBANG_MYRES' },
            },
        },
        fd = {
            label = 'Fire / Safety Equipment',
            groups = { fire = 0 },
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
                { name = 'WEAPON_FLASHLIGHT' },
                { name = 'WEAPON_FIREEXTINGUISHER' },
                { name = 'WEAPON_HALLIGAN' },
                { name = 'WEAPON_PIKE' },
                { name = 'WEAPON_PICKHEAD' },
                { name = 'WEAPON_FLATHEAD' },
                { name = 'WEAPON_SLEDGE' },
                { name = 'WEAPON_FORESTER' },
                { name = 'WEAPON_HYDRANT' },
                { name = 'WEAPON_REELBRANCH' },
                { name = 'WEAPON_FOAMBRANCH' },
            },
        },
        dot = {
            label = 'DOT Equipment',
            groups = { dot = 0 },
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
                { name = 'WEAPON_FLASHLIGHT' },
                { name = 'WEAPON_FIREEXTINGUISHER' },
                { name = 'WEAPON_HAMMER' },
                { name = 'WEAPON_WRENCH' },
            },
        },
        dispatch = {
            label = 'Dispatch Equipment',
            items = {
                { name = 'radio' },
                { name = 'bodycam' },
            },
        },
    },
}
